steps:
  - name: ":hear_no_evil: test"
    command: "unit-test.sh"
    key: "unit-test"
    artifact_paths:
      - "coverage/*"

  - wait
  
  - name: ":hear_no_evil: download"
    command: "download.sh"
